version: "3.7"

services:
  db:
    image: mariadb:10.7
    container_name: django-db
    restart: unless-stopped
    env_file:
      - ./config/.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - django-db-data:/var/lib/mysql
    expose:
      - 3306

  redis:
    image: redis:7-alpine
    container_name: django-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - django-redis-data:/data

  web:
    image: nginx:latest
    container_name: django-web
    restart: unless-stopped
    volumes:
      - django-app-blue-data:/app
      - django-app-green-data:/app
      - ./docker/config/nginx:/etc/nginx/conf.d
    ports:
      - 8000:8000

  celery-beat:
    image: django-backend:latest
    container_name: django-celery-beat
    restart: unless-stopped
    entrypoint: /app/celery-entrypoint.sh beat
    volumes:
      - django-app-blue-data:/app
      - django-app-green-data:/app
    depends_on:
        - db
        - redis
        - web

  celery-worker:
    image: django-backend:latest
    container_name: django-celery-worker
    restart: unless-stopped
    entrypoint: /app/celery-entrypoint.sh worker
    volumes:
        - django-app-blue-data:/app
        - django-app-green-data:/app
    depends_on:
        - db
        - redis
        - web

  django-app-blue:
    image: django-backend:latest
    container_name: django-app-blue
    restart: unless-stopped
    entrypoint: /app/server-entrypoint.sh
    volumes:
        - django-app-blue-data:/app
    depends_on:
        - db
        - redis
        - web

  django-app-green:
    image: django-backend:latest
    container_name: django-app-green
    restart: unless-stopped
    entrypoint: /app/server-entrypoint.sh
    volumes:
        - django-app-green-data:/app
    depends_on:
        - db
        - redis
        - web

volumes:
    django-app-blue-data:
    django-app-green-data:
    django-db-data:
    django-redis-data:
